let   teachers=[
    {
        id:1,
        username:'小乔',
        nickname:'乔妹',
        age:'3岁',
        gender:1,
        phone:'13545127253'
    },
    {
        id:2,
        username:'妲己',
        nickname:'一生只属于主人',
        age:'3岁',
        gender:1,
        phone:'13545127253'
    },
    {
        id:3,
        username:'大乔',
        nickname:'电梯流',
        age:'3岁',
        gender:1,
        phone:'13545127253'
    },
    {
        id:4,
        username:'凯',
        nickname:'帅',
        age:'3岁',
        gender:0,
        phone:'13545127253'
    },
    {
        id:5,
        username:'露娜',
        nickname:'月下无限连',
        age:'3岁',
        gender:1,
        phone:'13545127253'
    },
    {
        id:6,
        username:'夏侯惇',
        nickname:'渣男',
        age:'3岁',
        gender:0,
        phone:'13545127253'
    },
    {
        id:7,
        username:'孙悟空',
        nickname:'齐天大圣',
        age:'3岁',
        gender:0,
        phone:'13545127253'
    },
    {
        id:8,
        username:'耀',
        nickname:'星空闪耀',
        age:'3岁',
        gender:0,
        phone:'13545127253'
    },
    {
        id:9,
        username:'马超',
        nickname:'超哥',
        age:'3岁',
        gender:0,
        phone:'13545127253'
    },

]

module.exports= teachers